{{- if not .Values.s3.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rbt.s3SecretName" . }}
  labels:
    {{- include "rbt.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key-id: {{ .Values.s3.accessKeyId | quote }}
  secret-access-key: {{ .Values.s3.secretAccessKey | quote }}
{{- end }}
